---
title: ""
output: html_document
---


------------------------------------------------------------------------------------

#  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; Victoria Li

**Tel: (647)-517-2938** &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp; **Email: v42li@uwaterloo.ca**  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; **Open PDF:**  <a href="resume_pdf.pdf" download>Victoria-Resume</a>

**Education: Candidate for Biomedical Engineering – BASc**  &emsp;&emsp;  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; **Home: Thornhill, Ontario L4J7V3** 


------------------------------------------------------------------------------------

## Summary of Qualifications
  + Experienced in C# and Java by producing games using graphic user interface, receiving a grade of A+
  + Familiarity with tools such as Eclipse, Visual Studio Code and automation
  + Currently learning C++ in a data structures and algorithms course
  + Impressive leadership, communication and initiative skills in team projects by achieving top 10 internationally in the integrated marketing campaign event

## Awards
  + Recipient of Waterloo <font color='red'>**President’s Scholarship**</font>
  + <font color='red'>**Student Council Award**</font> (2019)
    Demonstrated leadership and initiative within the school community
  + DECA (Distributive Executive Clubs of America) <font color='red'>**Internationals Top 10**</font> (2019)
  + <font color='red'>**Gold championship**</font> volleyball medal - Ontario Volleyball Association (2015)

## Projects
  **BUSINESS EXECUTIVE/MAYA MEMBER** – UW Nanorobotics Group Current

  + Rebuilt the website to update recent projects (MAYA, Vision) and accomplishments using WordPress to maintain an online presence
  + Created and delivered presentations to funding committees
    Received 90% of funding requests from three sources which allowed the team to make further progress in their projects
  + Performed superconductor testing with vibrometers and collected velocity and frequency data to create a stable flux system
  
  **UNLIMBITED TEAM MEMBER** – Biomechatronics Waterloo Current
  
  + Attended sessions on machine learning using Python for medical devices
  + Took imitative to print parts of a prosthetic hand using 3D technology
  
  **HACKER (HACKATHON)** – Starterhacks Jan 2020

  + Developed a web page using HTML and CSS for volunteers and homeless shelters to connect, and used C# to create a weighting/rank system
  
  **TEAM LEAD** – BME 161 Design Project Sept 2019 – Dec 2019

  + Developed and designed a medium fidelity product to solve a problem space for deaf users to better detect their surroundings
  + Prototyped the device using 3D printing technology and SolidWorks
    Received praise from the associate chair of Systems Design Engineering
  
  **JAVA PROJECTS** – Thornhill Secondary School June 2018

  + Designed the components of the graphics and programmed the leaderboards and controlling the fish movement across the screen
  + Developed a variety of test cases to perform quality tests to ensure the game runs smoothly with no errors

  **PRESIDENT** – HOSA (Health Occupations Students of America) Sept 2018 – June 2019

  + Organized weekly meetings and increased member engagement from previous years by 20% (30 to 37 members) by running campaigns

## Work Experience
  **TEACHING ASSISTANT** – Spirit of Math Sept 2016 – June 2019

  + Reinforced lessons presented by teachers by reviewing key material and implementing extra help sessions to improve overall grades
  + Recommended for individual one-on-one tutoring sessions
  
  **SERVER** – Marigolds and Onions Jul 2015 – Aug 2016
  
  + Provided high quality customer service by communicating to Rogers Cup volunteer and media personnel and received praise from manager
  
## Volunteer Work 
  **York University Science**
  
  + Engagement Camp Counsellor - Planned and organized
activities with limited resources for youth to inspire their interest in science and was able to increase engagement for every session
  
  **Night It Up General Volunteer**
  
  + Raised funds for the ALS double play beneficiary by providing youth with hands-on activities
